name: CI/CD - PR Approval-Based Deployment1

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  
  push:
    branches:
      - main

jobs:
  validate:
    name: "🔍 Validate Code & Plan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup tools
        run: |
          echo "Install tools here like Terraform, Node.js, etc."

      - name: Run Terraform Plan (example)
        run: |
          echo "Running Terraform plan..."
          # terraform init
          # terraform plan

      - name: Run Linter / Unit Tests
        run: echo "Linter or Unit Test execution here"
  
  deploy-staging:
    name: "🚀 Deploy to staging"
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Stage (example)
        run: |
          echo "Deploying to Stage..."

  deploy:
    name: "🚀 Deploy to Production (Post-Approval)"
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: prod  # This will pause job and require manual approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Prod (example)
        run: |
          echo "Deploying to Production..."
          # terraform apply -auto-approve
          # or kubectl apply -f
