name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            style
            perf
            ci
          requireScope: false
          subjectPattern: '^(.*)\(WI-\d+\)$'
          subjectPatternError: '❌ PR title must end with a work item in format (WI-1234)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
