name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            style
            perf
            ci
          requireScope: false
         # This pattern enforces: <type>: (TEL|WI-xxxx) <description>
          subjectPattern: '^(feat|fix|chore|docs|refactor|test|style|perf|ci): \((TEL|WI)-\d+\) .+'
          subjectPatternError: |
            ❌ PR title format is invalid.
            ➤ Use this format: <type>: <description> (TEL-1234) or (WI-1234)
            ✅ Example: feat: add user login page (TEL-1234)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
