name: CI/CD - PR Approval-Based Deployment

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled]
  
  push:
    branches:
      - main

jobs:
  # Call the reusable validation workflow
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      environment: 'all'

  # Call the reusable staging deployment workflow
  deploy-staging:
    uses: ./.github/workflows/deploy-staging.yml
    needs: validate
    if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy-staging'))
    with:
      environment: 'staging'
      branch: ${{ github.event.pull_request.head.ref || github.ref_name }}

  # Call the reusable production deployment workflow (only on push to main)
  deploy-production:
    uses: ./.github/workflows/deploy-production.yml
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      environment: 'production'
      require-approval: true
